apiVersion: v1
kind: Pod
metadata:
  labels:
    run: deployment
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        run: deplyoment
    spec:
      containers:
      - image: ilyas615/pacman:latest
        name: pacman
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
